### PR TITLE
Improved current format of binary data for serialization / deserialization values and other fixes.

### PR DESCRIPTION
**Pull request by YPermitin**
- #26 Improved current format of binary data for serialization / deserialization values
- #19 Added support for NULL values
- Added CustomObject converter for working with classes and structures.
- #48 Fixed for complex objects
- Added unit tests for new features and improvements.
- Using checking for writable properties instead of checking for virtual properties. Updated unit tests for this.

This is first step for 2.0 release. After code review I will working on the next PR.
New format of binary serialization / deserialization based on the next structure:
- Internall type
- Type info size
- Type info
- Data size
- Data

For NULL values stored only internall type. In the future I will disable type info block for primitive types and none valued types.

Also we need a detailed description of the binary data format. I can do it after the release 2.0.

### CODE REVIEW

**Comment by lukasz-pyrzyk** [comment]
Hi @YPermitin ! Wow, what a PR!

I will review it today/tomorrow morning

**Comment by YPermitin** [comment]
@lukasz-pyrzyk Ok) I will be happy for any critics abd suggestions. :)

**Comment by lukasz-pyrzyk** [comment]
PR looks okay, i walk through the code using github. 

Can you apply changes? After it, I will merge and check again code using VS :)

**Comment by YPermitin** [comment]
@lukasz-pyrzyk okey. I will apply all changes today.

**Comment by YPermitin** [comment]
@lukasz-pyrzyk I commited all changes, what I want to do on the first step.
I applied all changes on the Develop branch.

I will be waiting for bad and good words :)

**Pull request merged**
